// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlHx-8rOZD6BPQDBB4eyAbcdG4UvTQGkI',
    appId: '1:389109026175:web:372d5fc4198b289f201e4a',
    messagingSenderId: '389109026175',
    projectId: 'nexus-legend',
    authDomain: 'nexus-legend.firebaseapp.com',
    storageBucket: 'nexus-legend.firebasestorage.app',
    measurementId: 'G-0YM16GZW7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKSWWorCTFbpzaA7RZ6z29s49AsEOzY_4',
    appId: '1:389109026175:android:dc6ae76e86a2ec3f201e4a',
    messagingSenderId: '389109026175',
    projectId: 'nexus-legend',
    storageBucket: 'nexus-legend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB4qWTGStpE1THoQXwRnamLVdL9nuwJYE',
    appId: '1:389109026175:ios:3936c73535774254201e4a',
    messagingSenderId: '389109026175',
    projectId: 'nexus-legend',
    storageBucket: 'nexus-legend.firebasestorage.app',
    iosBundleId: 'com.example.nexusLegend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB4qWTGStpE1THoQXwRnamLVdL9nuwJYE',
    appId: '1:389109026175:ios:3936c73535774254201e4a',
    messagingSenderId: '389109026175',
    projectId: 'nexus-legend',
    storageBucket: 'nexus-legend.firebasestorage.app',
    iosBundleId: 'com.example.nexusLegend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlHx-8rOZD6BPQDBB4eyAbcdG4UvTQGkI',
    appId: '1:389109026175:web:77fed6c4058f2145201e4a',
    messagingSenderId: '389109026175',
    projectId: 'nexus-legend',
    authDomain: 'nexus-legend.firebaseapp.com',
    storageBucket: 'nexus-legend.firebasestorage.app',
    measurementId: 'G-Z4VJWRLDPQ',
  );
}
